# all available settings of specific linters
linters-settings:
  goimports:
    local-prefixes: github.com/GetStream/govaluate
  errcheck:
    check-type-assertions: false
    check-blank: false
  gocritic:
    disabled-checks:
      - whyNoLint
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    settings:
      hugeParam:
        sizeThreshold: 364
      rangeValCopy:
        sizeThreshold: 364
        skipTestFuncs: true
  gocyclo:
    min-complexity: 50

linters:
  enable-all: true
  disable:
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - lll
    - stylecheck
    - wsl
    - whitespace
